version: 0.0
os: linux
files:
  - source: /atc
    destination: /var/www/html/atc
  - source: /chinese
    destination: /var/www/html/chinese
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root