version: 0.0
os: linux
files:
  - source: https://github.com/saifatc/atc.git
    destination: /var/www/html/atc
  - source: https://github.com/saifatc/chinese.git
    destination: /var/www/html/chinese
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root