version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
hooks:
  BeforeInstall:
    - location: scripts/pre_install_script.sh
      timeout: 300
  AfterInstall:
    - location: scripts/post_install_script.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/start_script.sh
      timeout: 300
