version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get install -y php7.1
  pre_build:
    commands:
      - composer install
  build:
    commands:
      - phpunit tests
artifacts:
  files:
    - '**/*'
