version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get install -y  software-properties-common
      - LC_ALL=C.UTF-8 add-apt-repository -y ppa:ondrej/php
      - apt-get update
      - apt-get install -y php7.1
  pre_build:
    commands:
      #Install composer
      - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
      - php composer-setup.php ;
      - php -r "unlink('composer-setup.php');" ;
      - mv composer.phar /usr/local/bin/composer
  commands:
      - echo Installing composer deps
      - composer install --no-progress --no-suggest
artifacts:
  files:
    - '**/*'
