version: 0.2

phases:
  install:
    commands:
      - apt-get install -y php70
      - apt-get php70-mysqlnd
  pre_build:
    commands:
      - composer install
  build:
    commands:
      - phpunit tests
artifacts:
  files:
    - '**/*'
